#!/bin/sh
# Install a `mitui` launcher into ~/.local/bin without touching site-packages.
set -e

DIR=$(cd "$(dirname "$0")" && pwd)
BIN="${HOME}/.local/bin"

PY=""
for candidate in python3 python; do
    if command -v "$candidate" >/dev/null 2>&1; then
        if "$candidate" -c 'import sys; sys.exit(0 if sys.version_info >= (3, 8) else 1)'; then
            PY=$(command -v "$candidate")
            break
        fi
    fi
done
if [ -z "$PY" ]; then
    echo "error: python 3.8 or newer is required" >&2
    exit 1
fi
if ! "$PY" -c 'import curses' 2>/dev/null; then
    echo "error: this python has no curses module." >&2
    echo "  Debian/Ubuntu: sudo apt install python3-curses" >&2
    echo "  Fedora:        sudo dnf install python3-libs" >&2
    exit 1
fi

mkdir -p "$BIN"
cat > "$BIN/mitui" <<EOF
#!/bin/sh
# generated by mihomo-tui/install.sh
PYTHONPATH="$DIR\${PYTHONPATH:+:\$PYTHONPATH}" exec "$PY" -m mitui "\$@"
EOF
chmod +x "$BIN/mitui"
echo "installed $BIN/mitui  (source: $DIR, python: $PY)"

case ":$PATH:" in
    *":$BIN:"*) ;;
    *) echo "note: $BIN is not on your PATH -- add this to your shell rc:"
       echo "      export PATH=\"\$HOME/.local/bin:\$PATH\"" ;;
esac

if command -v mihomo >/dev/null 2>&1; then
    echo "mihomo found: $(command -v mihomo)"
else
    echo "mihomo core not found. Install it with your package manager, or run:"
    echo "      mitui install-core"
fi
echo
echo "next: mitui sub add '<your subscription URL>'  then  mitui"
